name: jbu
favicon: null
layout_spectrum: 0.5384873615112156
typography_spectrum: 0.05612606089562178
title: johannes buchmann berlin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.024674437008798122
  lightness: 0.8779696114361286
  saturation: 0.62928411597386
  rhythmicContrast: 0.024004734819754958
purpose: []
