title: johannes buchmann berlin
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7007169
  brandStrength: 0.2383513
  lightness: 0.8512545
  brandColors:
    - '#F0F1E9'
    - '#312E28'
    - '#BEB3A3'
    - '#878889'
    - '#4BA3B2'
  rhythmicContrast: 0.8010753
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: jbu
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3548387
layout_spectrum: 0
